# Generated by Django 2.2.6 on 2019-10-31 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Pro',
        ),
    ]
