# Generated by Django 2.2.6 on 2019-10-31 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_product_featured'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
